### ISSUE TITLE
svm_options - Enable all parameters for power users in SVM

### ISSUE THREAD

**Issue by kudkudak** [gmum/gmum.r#442]
KlaR supports all svmlight options by `svm.options` parameter. In general I think we should do something similar. That is we can have `svm.options` parameter that accepts just console parameters that we will parse and pass appropriately to svmlight and libsvm.

http://cran.r-project.org/web/packages/klaR/klaR.pdf

**Comment by ktalik** [comment]
What is a priority of command-line arguments? Should we overwrite them with our own parameters (if passed) or do the opposite? Opposite would be much easier.

KlaR does not have such problem, since they are using binary SVMLight with consistent (original) parameters.

**Comment by kudkudak** [comment]
I think we should inform user about the conflict (R or C++ warning) and pick any of the two.

**Comment by kudkudak** [comment]
Please note that this issue is also about Libsvm, it would be inconsistent to have this argument only for svmlight

**Comment by ktalik** [comment]
It is already planned for both libraries (see your first message).
