### ISSUE TITLE
Installation from wiki does not work!

### ISSUE THREAD

**Issue by lejlot** [gmum/gmum.r#477]
Installation from
https://github.com/gmum/gmum.r/blob/dev/src/README.md
does not work (install finished, loading too, but there are no modules accessible)

    > devtools::install_github("gmum/gmum.r")
    Downloading github repo gmum/gmum.r@master
    Installing gmum.r
    '/usr/lib/R/bin/R' --vanilla CMD INSTALL  \
      '/tmp/RtmpBlIZLo/devtools3b5e32231f36/gmum-gmum.r-476e083'  \
      --library='/home/lejlot/R/x86_64-pc-linux-gnu-library/3.0' --install-tests 

    * installing *source* package ‘gmum.r’ ...
    ** libs
    g++ -I/usr/share/R/include -DNDEBUG   -I"/home/lejlot/R/x86_64-pc-linux-gnu-library/3.0/Rcpp/include"   -fpic  -O3 -pipe  -g  -c hello_gmum.cpp -o hello_gmum.o
    In file included from hello_gmum.cpp:1:0:
    hello_gmum.h:1:14: warning: extra tokens at end of #ifndef directive [enabled by default]
     #ifndef _gmum-r_RCPP_HELLO_WORLD_H
                  ^
    hello_gmum.h:2:14: warning: missing whitespace after the macro name [enabled by default]
     #define _gmum-r_RCPP_HELLO_WORLD_H
                  ^
    g++ -shared -o gmum.r.so hello_gmum.o -L/usr/lib/R/lib -lR
    installing to /home/lejlot/R/x86_64-pc-linux-gnu-library/3.0/gmum.r/libs
    ** R
    ** inst
    ** preparing package for lazy loading
    ** help
    Ostrzeżenie: /tmp/RtmpBlIZLo/devtools3b5e32231f36/gmum-gmum.r-476e083/man/gmum-utils-package.Rd:31: All text must be in a section
    Ostrzeżenie: /tmp/RtmpBlIZLo/devtools3b5e32231f36/gmum-gmum.r-476e083/man/gmum-utils-package.Rd:32: All text must be in a section
    *** installing help indices
    ** building package indices
    ** testing if installed package can be loaded
    * DONE (gmum.r)
    > library(gmum.r)
    Ładowanie wymaganego pakietu: Rcpp
    > SVM
    BŁĄD: nie znaleziono obiektu 'SVM'

**Comment by marcinMarcin** [comment]
You have used master branch. Please use dev instead using **ref** argument:
```{R}
devtools::install_github("gmum/gmum.r", ref="dev")
```
Installation instruction improved.
