### ISSUE TITLE
Results of "highlevel" SVM tests - minor to major errors

### ISSUE THREAD

**Issue by lejlot** [gmum/gmum.r#478]
1. We do not define environment, compare **DONE**

        > svm
        function (x, ...) 
        UseMethod("svm")
        <environment: namespace:e1071>
        > SVM
        function(x, ...)
            UseMethod("SVM")
        <environment: 0x7aaca38>

2. Shouldn't I be able to predict on a single vector? **Done** 

        > X <- matrix(c(c(0,1), c(1,0)), 2)
        > y <- c(0, 1)
        > c <- SVM(X, y)
        optimization finished, #iter = 1
        Komunikat ostrzegawczy:
        In SVM.default(X, y) : It is recommended to pass y as factor
        > predict(c, X[1,])
        Błąd w .local(object, ...) : Please provide matrix or data.frame

3. Why is there a warning "Only limited plotting is currently supported for multidimensional data" when I plot the above model? It has 2 dimensions. **Done** 

4. We have $predict and $sparse_predict among public methods, but none of them works **Done** 

        > c$predict(X) # does nothing? no error nor output
        > c$predict( )
        BŁĄD: could not find valid method
        > c$sparse_predict(X)
        BŁĄD: could not find valid method
        > c$sparse_predict()
        BŁĄD: could not find valid method

5. Multi class fails for very simple case (there is no default class.type) **Done** 

        > X <- matrix( c(1,2,3,4,5,6), 3)
        > X
             [,1] [,2]
        [1,]    1    4
        [2,]    2    5
        [3,]    3    6
        > c <- SVM(X, c(1,2,3))
        Błąd w class.type == "one.versus.all" : brakuje 'class.type'
        Dodatkowo: Komunikat ostrzegawczy:
        In SVM.default(X, c(1, 2, 3)) : It is recommended to pass y as factor

6. Plotting for multiclass fails if labels are not passed as factors (X as above) **Done** 

        > c <- SVM(X, c(1,2,3), class.type="one.versus.all")
        optimization finished, #iter = 1
        optimization finished, #iter = 2
        optimization finished, #iter = 1
        Komunikat ostrzegawczy:
        In SVM.default(X, c(1, 2, 3), class.type = "one.versus.all") :
          It is recommended to pass y as factor
        > plot(c)
        BŁĄD: A continuous variable can not be mapped to shape
        Dodatkowo: Komunikat ostrzegawczy:
        In plot.svm(x, X = X, cols = cols, radius = radius, radius.max = radius.max) :
          Only limited plotting is currently supported for multidimensional data

7. Multi-class svm fails when trying to plot a contour plot **Done** 
8. There is some weird message when plotting contour plot of very simple model **Done** 

        > c <- SVM(X, as.factor(c(1,2,1)))
        optimization finished, #iter = 2
        > plot(c, mode="contour")
        Komunikat ostrzegawczy:
        Removed 1 rows containing missing values (geom_segment). 
        > X
             [,1] [,2]
        [1,]    1    4
        [2,]    2    5
        [3,]    3    6

9. Multiclass SVM does not have any fields that SVM has, in particular we do not have access to "small" models ($models field contains list of appropiate size, but no models inside)

        > c
        [1] "Support Vector Machine, multiclass.type: one.versus.one, core: libsvm, kernel: linear"
        [1] "3 classes"
        > c$
        c$models      c$X           c$pick        c$call        c$kernel      
        c$class.type  c$Y           c$levels      c$core   
        > c$models
        [[1]]

        [[2]]

        [[3]]

10. $getPrediction() returns nothing? **Done** 

        > c <- SVM(X, as.factor(c(1,2,1)))
        optimization finished, #iter = 2
        > c$getPrediction()
             [,1]

11. 2e fails (X still the same) **Done**

        > c <- SVM(X, as.factor(c(1,2,1)), kernel='rbf', C=1000, prep="2e")

        error: addition: incompatible matrix dimensions: 1x1 and 2x2

        BŁĄD: addition: incompatible matrix dimensions: 1x1 and 2x2
        > c <- SVM(X, as.factor(c(1,2,1)), kernel='linear', C=1000, prep="2e")

        error: addition: incompatible matrix dimensions: 1x1 and 2x2

        BŁĄD: addition: incompatible matrix dimensions: 1x1 and 2x2

12. transductive.learning=TRUE should imply library=svmlight if none is provided **Done** 

        > t <- SVM(X, as.factor(c(1,2,0)), transductive.learning=TRUE)
        Błąd w SVM.default(X, c(1, 2, 0), transductive.learning = TRUE) : 
          Error 20 : bad library, transductive learning is supported only by svmlight

13. plotting transductive fails **Done** 

        > t <- SVM(X, as.factor(c(1,2,0)), transductive.learning=TRUE, core="svmlight")
        > plot(t)
        Błąd w `levels<-.factor`(`*tmp*`, value = c("1", "2")) : 
          number of levels differs

14. Contour plots do not have legend (why?) **Done**

**Comment by igorsieradzki** [comment]
Done: 2, 3, 4, 10

**Comment by igorsieradzki** [comment]
Done: 5, 6, 7, 8, 12, 13, 14
9 is tricky or I don't get `R`, to discuss.
Additionally I've added small margin to contour plots and found another issue with plot after our last meeting changes.

**Comment by lejlot** [comment]
what do you mean by "small margin to contour plots "?

**Comment by igorsieradzki** [comment]
Margin to grid, before it was generated from min(x) to max(x) etc. which resulted it drawing points on the border of  a plot, like this (bottom plot)
![](https://github.com/gmum/gmum.r/blob/dev/doc/img/svm_readme.png?raw=true)

**Comment by kudkudak** [comment]
Did namespace issue, evalqOnLoad takes `where` argument which after assigning `asNamespace("gmum.r")` fixed the issue

**Comment by sacherus** [comment]
All tasks done. Can close.
