### ISSUE TITLE
Results of "highlevel" CEC tests - minor to major errors

### ISSUE THREAD

**Issue by lejlot** [gmum/gmum.r#479]
1. Cluster names are old ("full", "sphere" etc. instead of "fixed", "spherical") etc. **DONE**
2. predict does not work **DONE**
 a) when applied to matrix - it fails completely
 b) when applied to vector - it returns invalid cluster id
3. We do not define environment (see issue for SVM) **DONE**
4. Plotting still uses circles, it should be changed so we plot "dots" (please use the same plotting style as SVM) **DONE**
5. We are missing ability to plot multidimensional data in a projected form (method="pca", as SVM) **DONE**
6. One error message is enough **DONE**

        > a=matrix(rnorm(1000), 10)
        > cec<-CEC(a, k=1)
        There are degenerated clusters! You should try run CEC with other parametersThere are degenerated clusters! You should try run CEC with other parametersThere are degenerated clusters! You should try run CEC with other parametersThere are degenerated clusters! You should try run CEC with other parametersThere are degenerated clusters! You should try run CEC with other parametersThere are degenerated clusters! You should try run CEC with other parametersThere are degenerated clusters! You should try run CEC with other parametersThere are degenerated clusters! You should try run CEC with other parametersThere are degenerated clusters! You should try run CEC with other parametersThere are degenerated clusters! You should try run CEC with other parameters> 

7. And plot dies for the above **DONE**

        > plot(cec)
        Błąd w plot.new() : figure margins too large

8. In one of the issues @kjurek used a trick to ensure that determinant is never zero, here - it is, and energy is -inf "**DONE**"

**Comment by kjurek** [comment]
9. Change interface of mixed cluster type; should be like this: params.list=(cluster type, rep_num)

**Comment by kjurek** [comment]
4, 6 and interface of mixed cluster fixed.
Now every cluster parameter can have k attribute (default k=1) which indicates how many clusters of this type should be created. Example usage:
```
library(gmum.r)
p1 = list(method.type='spherical', k=3)
p2 = list(method.type='diagonal', k=2)
data(cec_t_set)
c <- CEC(x=Tset, params.mix=list(p1,p2))
plot(c, ellipses=TRUE, centers=TRUE)
```
![mix](https://cloud.githubusercontent.com/assets/1937406/7667460/373f2294-fc09-11e4-9565-589592b6332f.png)

**Comment by lejlot** [comment]
Circles could be much smaller :-)

**Comment by marcinMarcin** [comment]
8. is the problem of CEC model. Skipped.

**Comment by marcinMarcin** [comment]
7 resolved

**Comment by marcinMarcin** [comment]
We have now ability to use method="pca" in CEC plot. @kudkudak thanks for pair programming.

**Comment by kudkudak** [comment]
Pair programming for life

**Comment by kudkudak** [comment]
Merged into dev. Closing, awesome job CEC team !
