### ISSUE TITLE
Results of "highlevel" GNG tests - minor to major errors

### ISSUE THREAD

**Issue by lejlot** [gmum/gmum.r#480]
Done 1. Online learning requires specifing dataset dimensionality (why? It should read it from the first sample), furthermore - produces very ugly error 

        > gng <- GNG(train.online=TRUE)
        ERROR: incorrect dimensionality
        Błąd w paste(code, ": ", message, sep = "") : 
          nie znaleziono obiektu 'ERROR_BAD_PARAMS'

Done 2. We can save a GNG model but there is no "load"
DONE 3. Something is wrong with predicting centroid (predict and predictComponent work fine) using model from getting started "Optimized version of GNG"

        > predictCentroid(gng, sphere.dataset)
        Błąd w is.vector(x) : brakuje argumentu "x" a brak wartości domyślnej.

DONE 4. Both "optimized" and "normal" GNG have the same name in summary, maybe "optimized" should introduce himself as "Optimized Growing Neural Gas"?
DONE 5. Optimized gng (trained with code from getting started) can predict using `predict(gng, sphere.dataset)` but not using gng$predict (only for whole dataset, for single vectors both work fine)

        > gng$predict(sphere.dataset)
        BŁĄD: Wrong example dimensionality

DONE 6. We do not check parameters range in plots

        > plot(gng, vertex.size=-1)
        Błąd w symbols(x = coords[, 1], y = coords[, 2], bg = vertex.color,  : 
          invalid symbol parameter

        > plot(gng, vertex.color=predictComponent(gng, sphere.dataset))
        Komunikaty ostrzegawcze:
        1: In if (vertex.color == "label") { :
          warunek posiada długość > 1 i tylko pierwszy element będzie użyty
        2: In if (vertex.color == "cluster") { :
          warunek posiada długość > 1 i tylko pierwszy element będzie użyty
        3: In if (vertex.color == "fast_cluster") { :
          warunek posiada długość > 1 i tylko pierwszy element będzie użyty
        4: In if (vertex.color == "none") { :
          warunek posiada długość > 1 i tylko pierwszy element będzie użyty

DONE 7. There is some problem with compatibility between datasets. We cannot use GNG on svm dataset

        > g2 <- GNG(svm.breastcancer.dataset[,-1])
        [1] "Training offline"
        BŁĄD: not compatible with requested type
        > g2 <- GNG(svm.breastcancer.dataset)
        [1] "Training offline"
        BŁĄD: not compatible with requested type
        > g2 <- GNG(svm.breastcancer.dataset$X1)
        BŁĄD: expecting a single value

NOT DONE (this is essentially another function, which predicts component that is closest to point. I agree it is not very intuitive but we can add it as another issue later. I added possibility to pass colors as list) 8. It would be great to be able to easily plot with color dependent on the component (as we already have predictComponent)

        > plot(gng, vertex.color="component")
        Błąd w symbols(x = coords[, 1], y = coords[, 2], bg = vertex.color,  : 
          niepoprawna nazwa koloru 'component'

DONE 9. Even seeded GNG is not deterministic. X is a vector of random 500 samples from 2d standard gaussian

        > gng <- GNG(X, seed=1)
        [1] "Training offline"
        [1] "Iteration 198"
        [1] "Iteration 200"
        [1] "Iteration 200"
        > gng <- GNG(X, seed=1)
        [1] "Training offline"
        [1] "Iteration 199"
        > gng <- GNG(X, seed=1)
        [1] "Training offline"
        [1] "Iteration 198"
        [1] "Iteration 200"
        [1] "Iteration 200"
        > gng <- GNG(X, seed=1)
        [1] "Training offline"
        [1] "Iteration 200"
        [1] "Iteration 200"
        > gng <- GNG(X, seed=1)
        [1] "Training offline"
        [1] "Iteration 200"
        [1] "Iteration 200"

DONE 10. Ugly messages when parameters are wrong

        > gng <- GNG(X, alpha=123)
        ERROR: alpha should be in range [0,1]
        Błąd w paste(code, ": ", message, sep = "") : 
          nie znaleziono obiektu 'ERROR_BAD_PARAMS'

DONE 11. Error message says that "alpha should be in range [0,1]" but does not accept alpha=0
DONE 12. Similarly to the above, max.nodes cannot be 2 (even though error message says it is ok)
DONE 13. If someone wants an online model, and provides data in X it should learn it (and not require dim!)

        > gng <- GNG(X, max.nodes=6, train.online=TRUE)
        ERROR: incorrect dimensionality
        Błąd w paste(code, ": ", message, sep = "") : 
          nie znaleziono obiektu 'ERROR_BAD_PARAMS'
        > gng <- GNG(X, max.nodes=6, train.online=TRUE, dim=2)
        > plot(gng)
        NULL
        Komunikat ostrzegawczy:
        In .local(x, ...) : Empty graph

DONE (partially, I am pretty sure there are many language problems still) 14. Help has language mistakes, like " Every lambda iteration is added new vertex" should be "New vertex is added every lambda iterations"; "dim: Used for training online, specifies training example size" no it does not, it denotes example dimensionality.
DONE 15. Example from help does not work

        > data(wine, package="rattle")
        >      scaled.wine <- scale(wine[-1])
        > gng <- GNG(scaled.wine, labels=wine$Type, max.nodes=20)
        [1] "Training offline"
        BŁĄD: not compatible with requested type

**Comment by kudkudak** [comment]
Ad 1) I am aware of that, but that requires some additional changes to architecture and is not that problematic, I think. I can fix it when there are no other issues (are we taking here limes with time going to infinity? :) )

**Comment by kudkudak** [comment]
Ad2. `We can save a GNG model but there is no "load"`

There is `gngLoad` and `gngSave`?

Ad3 `Something is wrong with predicting centroid (predict and predictComponent work fine) using model from getting started "Optimized version of GNG"`

If you type `help(predictCentroid)` it shows usage with 3 arguments, I think it makes sense, because finding centroids is such a non defined task (many metrics) that it might be useful to leave this to user.

**Comment by kudkudak** [comment]
Remove $save.

**Comment by kudkudak** [comment]
Ad 1) ERROR: incorrect dimensionality
Błąd w paste(code, ": ", message, sep = "") : 
  nie znaleziono obiektu 'ERROR_BAD_PARAMS' 

Better error message

Ad 3) rename predictCentroid to findClosests and predictCentroid should do what centroids does currently

**Comment by kudkudak** [comment]
Done on gng branch. Some fixes are not full, but I believe it is good enough for now.
