### ISSUE TITLE
2e fails for:  X <- matrix( c(1,2,3,4,5,6), 3)

### ISSUE THREAD

**Issue by sacherus** [gmum/gmum.r#484]
> c <- SVM(X, as.factor(c(1,2,1)), kernel='rbf', C=1000, prep="2e")

error: addition: incompatible matrix dimensions: 1x1 and 2x2

BŁĄD: addition: incompatible matrix dimensions: 1x1 and 2x2
> c <- SVM(X, as.factor(c(1,2,1)), kernel='linear', C=1000, prep="2e")

error: addition: incompatible matrix dimensions: 1x1 and 2x2

BŁĄD: addition: incompatible matrix dimensions: 1x1 and 2x2J

X <- matrix( c(1,2,3,4,5,6), 3)
c <- SVM(X, as.factor(c(1,2,1)), kernel='rbf', C=1000, prep="2e")

**Comment by sacherus** [comment]
Found reson:
there is only one positive example, sa matrix is treated as vector by armadillo.

**Comment by sacherus** [comment]
Actually,
test case when we have only one class of example is degenerated, because we zeroing our data. We could add special case, when we have only one class and return error. Should we?
Yes we should.

**Comment by igorsieradzki** [comment]
Any updates? We would like to merge `svm-wrapper` to `dev` asap.

**Comment by sacherus** [comment]
Minor fix. Closing.
