### ISSUE TITLE
Build failed under Mac OS X 10.10

### ISSUE THREAD

**Issue by vsov** [gmum/gmum.r#487]
Compilation fails with

>error: invalid argument '--std=c++0x' not allowed with 'C/ObjC'
>make: *** [svmlight/svm_common.o] Error 1

(most recent version of Xcode and command line tools)

**Comment by kudkudak** [comment]
Thank you, we will investigate it as quickly as possible.

**Comment by kudkudak** [comment]
With @brunokam help we have hopefully fixed the main issue, we will close after your confirmation.

**Comment by kudkudak** [comment]
Closing for now, please let us know if there are any further issues
