### ISSUE TITLE
Another round of tests [mostly SVM]

### ISSUE THREAD

**Issue by lejlot** [gmum/gmum.r#489]
[DEV branch]

Major

0. [GENERAL] Great number of warnings during compilation - we should fix it in order to be accepted by CRAN
1. [GENERAL] What is "x"? and "y" .. and "x.cec" and "y.cec"

        > x
        standardGeneric for "x" defined from package "gmum.r"

        function (c) 
        standardGeneric("x")
        <environment: 0x83a88e0>
        Methods may be defined for arguments: c
        Use  showMethods("x")  for currently available ones.

  in general, we have horribly "clutered" namespace, compare what one sees after typing gmum.r::<tab><tab> and e1071::<tab><tab>

2. [SVM] Transductive SVM fails with multiclass (it is fine, but we should at least produce a nice error message)
3. [SVM] Plotting of Transductive SVM sometimes fails (iris is iris dataset loaded with data)

        > y = c(rep("a", 100), rep("b", 10), rep(0, 40))
        > svm.transduction <- SVM(iris[,-5], y, transductive.learning=TRUE, core="svmlight")
        Komunikat ostrzegawczy:
        In SVM.default(iris[, -5], y, transductive.learning = TRUE, core = "svmlight") :
          It is recommended to pass y as factor
        > plot(svm.transduction)
        Błąd w `levels<-.factor`(`*tmp*`, value = c("a", "b")) : 
          number of levels differs
        Dodatkowo: Komunikat ostrzegawczy:
        In .local(x, ...) :
          Only 2 dimension plotting is supported for multiclass. Plotting using cols parameter

Minor

1. [SVM] Preprocessing type is absent in "summary" when using multiclass
2. [SVM] In multiclass scenario model$models[[1]]$call has horribly long output (all variables are raw!)
3. [SVM] What is $pick in multiclass svm?
4. [SVM] Methods names are inconsistent between multiclass svm and single svm (kernel vs getKernel, etc.)
5. [SVM] Summary does not include C parameter, nor gamma
6. [SVM] SVM accepts gamma=0 (it should not)
7. [SVM] While provifing bad C creates nice error message, providing bad gamma outputs simply "bad SVM parameters", similarly putting C="a" outputs "not comatible with requested type"
8. [SVM] There are ugly messages when one tries to getW() on kernel SVM (W is not "decision boundary", by a hyperplane normal)

        ERROR: Decision boundary is not available with non-linear kernel
        BŁĄD: basic_string::_S_construct null not valid

9. [SVM] Transduction SVM has no iterations? getIterations() returns -1

**Comment by sacherus** [comment]
9. Probably fixed on svm-wrapper.

**Comment by igorsieradzki** [comment]
All SVM specific issues done on `svm-wrapper` branch, merging to `dev` soon.
