### ISSUE TITLE
R CMD Check - SVM documentation fixes

### ISSUE THREAD

**Issue by kudkudak** [gmum/gmum.r#506]
Please run `R CMD CHECK .` and clean all documentation related problems

**Comment by igorsieradzki** [comment]
Done, for reference chceck `svm.R` on `fix-r-check` branch.

**Comment by kudkudak** [comment]
You can erase setMethods from https://github.com/gmum/gmum.r/blob/dev/R/svm.R#L884 and as in CEC and GNG on latest commit change summary.svm -> summary.<RCPP CLASS NAME> etc. This should resolve S3 methods automatically.

For other methods we shouldn't use neither S3 nor S4 dispatching mechanism
