### ISSUE TITLE
R CMD Check - killall srand and rand

### ISSUE THREAD

**Issue by ktalik** [gmum/gmum.r#522]
We can do that with `RCpp` or `Boost`.

**Comment by ktalik** [comment]
Code is done on `task-522-killall-rand`. R check [no longer complains](https://travis-ci.org/gmum/gmum.r/builds/70638988#L2537) about `rand` and `srand` but there is indeterministic [fail of `test_cec_centroid_assignment.R#34`](https://travis-ci.org/gmum/gmum.r/builds/70638988#L2572). I'm not sure if it is related to [changes between `fix-r-check` and this task brach](https://github.com/gmum/gmum.r/compare/fix-r-check...task-522-killall-rand). CEC is not using `utils.h`/`utils.cpp` anywhere, is it?

**Comment by ktalik** [comment]
Maybe it's related to #523?

**Comment by kudkudak** [comment]
It should be according to @kjurek, a good way to check it would be merging in the branch with CEC seed and rerunning tests
