### ISSUE TITLE
Regression OSX compilation on fix-r-check

### ISSUE THREAD

**Issue by kudkudak** [gmum/gmum.r#532]
Fixes to Makevars have broken compilation on osx (missing gfortran). This is interesting, as we do not need gfortran, should be simple.

**Comment by ktalik** [comment]
Do you have any error messages? This is indeed interesting if we really do not need gfortran but still missing it at compilation (on ~~MACOS~~ OSX).

**Comment by kudkudak** [comment]
http://stackoverflow.com/questions/19920281/rcpparmadillo-compile-errors-on-os-x-mavericks - this is more complicated. We cannot just erase FLIBS

**Comment by kudkudak** [comment]
Double confirmed with @brunokam  (thanks!) that it is ok to add FLIBS. OSX can get into incorrect state, but it is not connected to our Makevars setting.
