### ISSUE TITLE
R Check - Subdirectory `src` contains: CMakeLists.txt

### ISSUE THREAD

**Issue by ktalik** [gmum/gmum.r#534]
Full related [R Check](https://travis-ci.org/gmum/gmum.r/builds/74463420#L2187) message:
```
* checking if this is a source package ... WARNING
Subdirectory ‘src’ contains:
  CMakeLists.txt README.md
```

What are your ideas? Is CMake ready? Can CMake be deployed to R build toolchain? We have two options to resolve this issue:
* If possible, migrate pkg building to CMake

or

* Leave `CMakelists.txt` on a temporary branch and remove it from `fix-r-check` (which implies `dev`) or maybe move to another directory?

**Comment by kjurek** [comment]
CMake works for me on branch dev with Linux and OSX.
I have no idea how to migrate pkg building to CMake, I wouldn't do that since @kudkudak said it is still not working on his Mac. Leaving it on temporary branch seems to be the best option for now imho.

**Comment by kudkudak** [comment]
Closing because we will create separate package anyway for CRAN, where we will delete files like this
