### ISSUE TITLE
Documentation fixes requests - first batch

### ISSUE THREAD

**Issue by kudkudak** [gmum/gmum.r#540]
[PL] Mozesz podzielic na osobne issue i poprzydzielac

1. ~~Co to jest "x" (strona 23 pdf)~~
2. ~~Strona 22 - "terminate" nie wiadomo do czego sie odnosi; podobnie jest z "run" etc. wygenerowana dokumentacja nie ma podzialu na submoduly~~
  i wszystko sie posklejalo. Da sie podzielic
3. ~~Czemu kazda metoda, w naglowku jest najpierw napisana trutypem a potem italiciem? Tam chyba powinien byc jakis opis italiciem?~~ (nie da sie nic zrobic)
4. ~~Mamy jakies dziwne rzeczy tam jak "Rcpp_CecModel-class" - tego chyba nie zrobimy~~
5. ~~Dokumentacja kaze mi ignorowac (21)~~
6. ~~Naprawic show~~

**Comment by igorsieradzki** [comment]
1. CEC @kjurek @marcinMarcin 
2. GNG i CEC mają kiepskie opisy i tytuły (ad. 4) @kudkudak @kjurek @marcinMarcin 
3. Nie wiem na razie jak to u siebie zreprodukować
4. j.w. tytuły są do zmiany, było w poprzednim issue
5. poszukam, ale wątpie
6. fixnę
7. fixnę

**Comment by igorsieradzki** [comment]
5. and 6. done and I believe CEC guys fixed 1.

**Comment by kudkudak** [comment]
I am closing because aggregate issues are hard to track. Opening specific issue for CEC to fix titles and descriptions, please open any other that are relevant.
