### ISSUE TITLE
CEC predict after$

### ISSUE THREAD

**Issue by kudkudak** [gmum/gmum.r#541]
> size=20
> x <- runif(size) 
> y <- runif(size) 
> df <- data.frame(x,y)
> cec <- CEC(df, k=3)
> cec$predict(df)
BŁĄD: not compatible with requested type
> predict(cec, df)
[1] 1 2 0 0 1 1 1 0 0 1 0 2 0 1 0 0 2 0 2 1

**Comment by marcinMarcin** [comment]
As agreed, cec$predict is now hidden.
