### ISSUE TITLE
SVM make demo/samples/* run

### ISSUE THREAD

**Issue by kudkudak** [gmum/gmum.r#558]
For example  #557. Created issue because I think I found more problems

**Comment by igorsieradzki** [comment]
Should be fixed, can someone run all svm samples to make sure?

**Comment by kudkudak** [comment]
Got `Error in system.file("data_sets", "svm", "large", "news20_part.RData",  : 
  no file found` in `svm.news20.times.spin.R`. It might be a good idea to add line downloading it using wget to the sample.
