### ISSUE TITLE
Travis doesn't run C++ tests

### ISSUE THREAD

**Issue by kudkudak** [gmum/gmum.r#562]
It would really make a difference to have them automatically running.

**Comment by ktalik** [comment]
C++ tests are [running](https://travis-ci.org/gmum/gmum.r/builds/81862728) and are green. However, after joining them together with the R part [test run exceeded 50 minutes](https://api.travis-ci.org/jobs/81920341/log.txt?deansi=true).

> One possible solution is to split up your test run.

This will be good when we divide our library to languages but for now I can try with a workaround. Compiling Boost during test run is an overkill, but Travis and Ubuntu aren't providing the latest version (same for g++-4.9). We could try with headers from `BH` R package (this will omit compilation) but someone please guide me how to get paths to them.

**Comment by kudkudak** [comment]
That's fantastic!

I have no idea how to get them, but pointer is that R compilation is linking them correctly, so we should grab it from one of the variables that we have from Makevars.

**Comment by kudkudak** [comment]
Oh - shoot, another thing is that we use **only static** boost headers, so we don't have to compile anything, maybe you can configure that in travis?

**Comment by ktalik** [comment]
Done. Enjoy the [green](https://travis-ci.org/gmum/gmum.r/builds/82020548) build logs from now :white_check_mark:

**Comment by kudkudak** [comment]
Fantastic @ktalik :)

One thing that concerns me - why the button says "build failing" on README.md?

**Comment by ktalik** [comment]
Because it referenced fix-r-check branch. Fixed.

**Comment by kudkudak** [comment]
:+1:
