### ISSUE TITLE
Installation (ubuntu 14.04, R 3.3.0 beta)

### ISSUE THREAD

**Issue by kvak** [gmum/gmum.r#582]
(2016-03-30 r70404)

Doing 

library("devtools")
devtools::install_github("gmum/gmum.r", ref="dev")

I get:

    ** testing if installed package can be loaded
    Error in .doLoadActions(where, attach) : 
      error in load action .__A__.1 for package gmum.r: loadModule(module = "cec", what = TRUE, env = ns, loadNow = TRUE): Unable to load module "cec": C stack usage  7973024 is too close to the limit
    Error: loading failed
    Execution halted
    ERROR: loading failed
    * removing ‘/usr/local/lib/R/site-library/gmum.r’
    Error: Command failed (1)

increasing the size of the R stack (by doing in the bash):

     $ ulimit -s unlimited

uncovers another problem (when installing after doing the above):

    ** testing if installed package can be loaded
    Error in .doLoadActions(where, attach) : 
      error in load action .__A__.1 for package gmum.r: loadModule(module = "cec", what = TRUE, env = ns, loadNow = TRUE): Unable to load module "cec": evaluation nested too deeply: infinite recursion / options(expressions=)?
    Error: loading failed
    Execution halted
    ERROR: loading failed
    * removing ‘/usr/local/lib/R/site-library/gmum.r’
    Error: Command failed (1)

**Comment by kudkudak** [comment]
Thanks for the bug report. Can you please try installing the package from CRAN?

**Comment by kvak** [comment]
I also did, and go the same problem.

**Comment by kudkudak** [comment]
@kvak Thanks. I will look into it whis week. It would be great if you can send me list of packages you have installed on your machine along with versions.

**Comment by kvak** [comment]
Dear Kudkudak, 

1> ip <- as.data.frame(installed.packages()[,c(1,3:4)])
1> rownames(ip) <- NULL
1> ip <- ip[is.na(ip$Priority),1:2,drop=FALSE]
1> print(ip, row.names=FALSE)
       Package     Version
            BH    1.60.0-1
        bitops       1.0-6
       caTools      1.17.1
          coda      0.18-1
      colorout       0.9-9
    colorspace       1.2-6
          curl       0.9.7
      DEoptimR       1.0-4
          DetR       0.0.3
      devtools      1.10.0
     dichromat       2.0-0
        digest       0.6.9
    doParallel      1.0.10
         e1071       1.6-7
       FastRCS       0.0.7
    fit.models      0.5-10
       foreach       1.4.3
           gbm       2.1.1
       ggplot2       2.1.0
         git2r      0.14.0
      gridBase       0.4-7
        gtable       0.2.0
          httr       1.1.0
        igraph       1.0.1
         irlba       2.0.0
     iterators       1.0.8
      jsonlite      0.9.19
      labeling         0.3
     lubridate       1.5.6
      magrittr         1.5
  MatrixModels       0.4-1
   matrixStats      0.15.0
       memoise       1.0.0
          mime         0.4
       munsell       0.4.3
       mvtnorm       1.0-3
           NMF      0.20.6
       openssl       0.9.2
         pcaPP      1.9-60
      pkgmaker        0.22
          plyr       1.8.3
      quantmod       0.4-5
      quantreg        5.19
            R6       2.1.2
  RColorBrewer       1.1-2
          Rcpp      0.12.4
 RcppArmadillo 0.6.700.3.0
     RcppEigen   0.3.2.5.1
      registry         0.3
      reshape2       1.4.1
         rjags         4-6
      rngtools       1.2.4
     robfilter         4.1
        robust      0.4-16
    robustbase      0.92-5
       robustX       1.1-4
         rrcov       1.3-8
    rstudioapi         0.5
        scales       0.4.0
       SparseM         1.7
       stringi       1.0-1
       stringr       1.0.0
           TTR      0.23-0
       whisker       0.3-2
         withr       1.0.1
        xtable       1.8-2
           xts       0.9-7
           zoo      1.7-12
       tkrplot      0.0-23

**Comment by kudkudak** [comment]
@kvak Thanks, I will look into this nevertheless and let you know if we solve it

**Comment by kudkudak** [comment]
Seems R. 3.3.0 is unstable, at least I have problems with it on my machine. Might be necessary to re-open this issue when 3.3.0 is released to devel, but for now leaving closed.
