### ISSUE TITLE
How does example_weights work?

### ISSUE THREAD

**Issue by skw90** [gmum/gmum.r#583]
Hi,

Not an issue but I couldn't find this information anywhere - how does example_weights work? does it work similarly to sklearn where

"Per-sample weights. Rescale C per sample. Higher weights force the classifier to put more emphasis on these points."? [link](http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC.fit)

Thank you!

**Comment by kudkudak** [comment]
Hello!

Please see this example: http://r.gmum.net/getting_started.html
